blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

logb/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('',include('blogs.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('',views.home,name="home"),
    path('about/',views.about_template,name="about"),
    path('login/',views.login_template,name="login"),
    path('register/',views.register_template,name="register"),
    
    path('api/signin/',views.signin,name="signin"),
    path('api/signup/',views.register,name="signup"),
    path('api/pregnancy-info/', views.user_pregnancy_info, name="pregnancy-info"),
    path('api/mood/', views.user_mood, name="mood"),
    path('api/user-data/', views.user_data, name="user-info"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime 

# Create your models here.
class UserPregnancyInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    weight = models.FloatField(null=True, blank=True)
    height = models.FloatField(null=True, blank=True)
    weeks_pregnant = models.IntegerField(null=True, blank=True)
    
class UserMood(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mood = models.CharField(max_length=500, null=True, blank=True)
    date = models.DateTimeField(default=datetime.now())

main/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password,check_password
# Create your views here.
def home(request,template_name="main/home.html"):
    return render(request,template_name)

def login_template(request,template_name="main/login.html"):
    return render(request,template_name)

def about_template(request,template_name="main/about.html"):
    return render(request,template_name)

def register_template(request,template_name="main/register.html"):
    return render(request,template_name)

def logout_url(request):
    if request.method == "POST":
        try:
            logout(request)
            status="successful"
            status_code = 200
            message = "Logout Successful"
        except:
            status="failed"
            status_code = 400
            message = "Some error occured"
        return JsonResponse(Response(status=status,status_code=status_code,message=message))

# @csrf_protect
@csrf_exempt
def login_api(request):
    if request.method == "POST":
        postdata = request.POST
        username = postdata['username']
        password = postdata['password']
        try:
            user = authenticate(username=username, password=password)
        except:
            user = None
        if user is not None:
            login(request,user)
            status = 'successful'
            status_code = '200'
            message = 'Successfully loggedin!'
        else:
            status = 'failed'
            status_code = '400'
            message = 'User not found'
    return JsonResponse(Response(status=status,status_code=status_code,message=message))

# @csrf_protect
@csrf_exempt
def register_api(request):
    if request.method == "POST":
        postdata = request.POST
        try:
            username = postdata['username']
            password = make_password(postdata['password'])
            first_name = postdata['first_name']
            last_name = postdata['last_name']
            email = postdata['email']
            try:
                user = User.objects.get(Q(username=username) | Q(email=email))
            except:
                user = None
            if user ==  None:
                User.objects.create(username=username,password=password,email=email,first_name=first_name,last_name=last_name)
                status = 'successful'
                status_code = '200'
                message = 'User Registered Successfully'
            else:
                status = 'failed'
                status_code = '400'
                message = 'Username or Email already Exists.'
        except Exception as e:
            status = 'failed'
            status_code = '400'
            message = 'Send all required details.'
        
    return JsonResponse(Response(status=status,status_code=status_code,message=message))

def Response(status,status_code,data={},message = "",):
    response = {'status':status,'status_code':status_code,'data':data,'message':message}
    return response

from .serializers import UserSerializer
from django.http import JsonResponse
from rest_framework.response import Response
from rest_framework import status, serializers
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth import authenticate, login
from .serializers import UserSerializer, UserMoodSerializer, UserPregnancyInfoSerializer
from django.contrib.auth.hashers import make_password
from . import models

@csrf_exempt
def register(request):
    postdata = request.POST
    try:
        user = User.objects.filter(Q(username=postdata['email']) | Q(email=postdata['email'])).count()
    except:
        user = None
    if not user:
        user = User.objects.create(username=postdata['email'],password=make_password(postdata['password']),email=postdata['email'],first_name=postdata['name'])
        login(request,user)
        return JsonResponse({"user": UserSerializer(user).data}	)
    else:
        return JsonResponse({"message": "Email already Exists."}, status=status.HTTP_400_BAD_REQUEST)
    
# Login API
@csrf_exempt
def signin(request):
    postdata = request.POST
    email = postdata['email']
    password = postdata['password']
    try:
        user = User.objects.get(username=postdata['email'])
    except:
        user = None
    print(user,email,password)
    if user and email and password:
        user = authenticate(username=email, password=password)
        if user:
            login(request,user)
            return JsonResponse({"user": UserSerializer(user).data})
        else:
            return JsonResponse({"message": "Invalid Credentials"}, status=status.HTTP_400_BAD_REQUEST)
    else:
        return JsonResponse({"message": "user not found"}, status=status.HTTP_400_BAD_REQUEST)
        
@csrf_exempt
def user_pregnancy_info(request):
    if request.method == "POST":
        weight = request.POST['weight']
        height = request.POST['height']
        weeks_pregnant = request.POST['weeks_pregnant']
        user = request.POST['user_id']
        if weight and height and weeks_pregnant and user:
            models.UserPregnancyInfo.objects.create(user_id=user,weight=weight,height=height,weeks_pregnant=weeks_pregnant)
            return JsonResponse({"message": "User Pregnancy Info Added"})
        else:
            return JsonResponse({"message": "User Pregnancy Info Not Added"})
        
@csrf_exempt
def user_mood(request):
    if request.method == "POST":
        mood = request.POST['mood']
        user = request.POST['user_id']
        if mood and user:
            models.UserMood.objects.create(user_id=user,mood=mood)
            return JsonResponse({"message": "User Mood Added"})
        else:
            return JsonResponse({"message": "User Mood Not Added"})
        
@csrf_exempt
def user_data(request):
    user_id = request.GET.get('user_id')
    print(user_id)
    if user_id:
        user = User.objects.get(id=user_id)
        user_pregnancy_info = models.UserPregnancyInfo.objects.get(user_id=user_id)
        user_mood = models.UserMood.objects.filter(user_id=user_id).order_by('-date')
        return JsonResponse({"user": UserSerializer(user).data,"user_pregnancy_info":UserPregnancyInfoSerializer(user_pregnancy_info).data,"user_mood":UserMoodSerializer(user_mood, many=True).data})
    else:
        return JsonResponse({"message": "User Not Found"})

templates/main/login.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- jQuery  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"
    integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <!-- <link rel="stylesheet" href="/Quiz/css/home.css"> -->
    <title>Login</title>
</head>

<style>
    * {
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }

    html,
    body {
        padding: 0px;
        margin: 0px;
        background-color: #ecf0f1;
    }

    #container {
        position: relative;
        display: flex;
        flex-direction: row;
        height: 480px;
        width: 25%;
        /* margin: 60px auto; */

    }


    #container form {
        position: absolute;
        display: flex;
        flex-direction: column;
        /* justify-content: center; */
        flex-wrap: wrap;
        text-align: center;
        height: 100%;
        /* width: 350%; */
        left: 0;
        top: 0;
        bottom: 0;
    }

    #container form :first-child {
        font-size: 100px;
        color: #16a085;
        align-items: center;
    }

    #container form :nth-child(2) {
        font-size: 24px;
        color: #fff;
    }

    #container input {
        border: 0px solid;
        outline-width: 0px;
        width: 300px;
        height: 40px;
        margin-left: 26px;
        font-size: 18px;
        font-weight: 600;
        background-color: #34495e;
        color: #fff;
        padding-left: 10px;
        border-bottom: 2px solid transparent;
        transition: all .3s ease;
    }

    ::placeholder {
        font-size: 18px;
        color: #bdc3c7;
    }

    #container button {
        border: 0px;
        width: 300px;
        height: 40px;
        margin-left: 26px;
        font-size: 18px;
        font-weight: 600;
        background-color: #16a085;
        color: #fff;
        cursor: pointer;
        transition: all .3s ease;
    }

    /*Hover effect*/

    #container button:hover {
        background-color: #ce4f48;
    }

    #container input:focus {
        border-bottom: 2px solid #16a085;
    }

    .signup_link{
        margin: 13px 0;
        text-align: center;
        font-size: 16px;
        color: #ffffff;
        
    }
    .signup_link a{
        color: #16a085;
        text-decoration: none;
    }
    .signup_link a:hover{
        color: #5A6EA5;
    }
</style>




<body class="bg-dark">
    <!-- body  -->

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" style="font-size: 0px" href="/"><b>
                <font size="5" color="#16a085" style="display: inline-block">LOG </font>
                <font size="6" color="#5A6EA5" style="display: inline-block"> B </font>
            </b></a> &nbsp &nbsp
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                    <li class="nav-item">
                        <a class="nav-link" href="/"><button type="button" class="btn btn-dark">Home</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/"><button type="button" class="btn btn-dark">My Blogs</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/"><button type="button" class="btn btn-dark">Write</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/"><button type="button" class="btn btn-dark">About</button></a>
                    </li>


                </ul>


            </div>
        </div>
    </nav>




    <!-- alerts -->




    <!--Login Form -->
    <br>
    <center>
        <div id="container">
            <br>
            <form>
                <i class="fas fa-user-circle"></i>
                <h2>Login</h2>
                <br>
                <br>
                <input type="email" id="email" name="email" aria-describedby="email" placeholder="Email" readonly
                onfocus="this.removeAttribute('readonly');">
                <h6 align="left" id="email_check"></h6>
                <br>
                <input type="password" id="login_password" name="login_password" placeholder="Password" readonly
                onfocus="this.removeAttribute('readonly');">
                <h6 align="left" id="login_password_check"></h6>
                <br>
                <button id="loginsubmitbtn" type="submit" onclick="login_info()">Login</button>
            </form>
           
        </div>
        <div class="signup_link">
            Not a member? <a href="{% url 'main:register'%}">Sign up</a>
        </div>
    </center>


    <script>
        window.addEventListener('mousedown', function () {

            console.log('hello');
        });

        $(document).ready(function () {
            $('#email_check').hide();
            $('#login_password_check').hide();


            var email_err = true;
            var login_password_err = true;


            $('#email').keyup(function () {
                email_check();
            })
            $('#login_password').keyup(function () {
                login_password_check();
            })
            


            function email_check() {
                var email_value = $('#email').val();
                if (email_value.length == '') {
                    $('#email_check').show();
                    $('#email_check').html("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Please enter your email name.");
                    $('#email_check').focus();
                    $('#email_check').css("color", "#ce4f48");
                    $('#email_check').css("align", "left");
                    email_err = false;
                    return false;
                }
                else {
                    $('#email_check').hide();
                }
            }
            function login_password_check() {
                var login_password_value = $('#login_password').val();
                if (login_password_value.length == '') {
                    $('#login_password_check').show();
                    $('#login_password_check').html("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Please enter your password.");
                    $('#login_password_check').focus();
                    $('#login_password_check').css("color", "#ce4f48");
                    login_password_err = false;
                    return false;
                }
                else {
                    $('#login_password_check').hide();
                }
            }
        

            $('#loginsubmitbtn').click(function () {
                email_err = true;
                login_password_err = true;

                email_check();
                login_password_check();
                
                if ((email_err == true) && (login_password_err == true)) {
                    return true;
                }
                else{
                    return false;
                }
            });

        });


        // for login Data 
        function login_info(){

            var email_form_value = document.getElementById("email").value;
            var login_password_form_value = document.getElementById("login_password").value;
            // console.log("email_value,login_password_value");
            console.log(email_form_value,login_form_password_value);

            
        }
                    // console.log(exam_time);



    </script>

    <!-- Optional JavaScript; choose one of the two! -->
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
        </script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <br><br><br><br><br>
</body>

</html>

templates/main/write.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Text Editor  -->
    <script src="https://cdn.ckeditor.com/4.20.1/standard/ckeditor.js"></script>

    <!-- jQuery  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"
        integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <!-- <link rel="stylesheet" href="/Quiz/css/home.css"> -->
    <title>Write</title>
</head>

<style>
    * {
        font-family: Verdana, Geneva, Tahoma, sans-serif;
    }

    html,
    body {
        padding: 0px;
        margin: 0px;
        background-color: dark;
    }
</style>




<body>
    <!-- body  -->

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" style="font-size: 0px" href="/"><b>
                    <font size="5" color="#16a085" style="display: inline-block">LOG </font>
                    <font size="6" color="#5A6EA5" style="display: inline-block"> B </font>
                </b></a> &nbsp &nbsp
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                    <li class="nav-item">
                        <a class="nav-link" href="/"><button type="button" class="btn btn-dark">Home</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/"><button type="button" class="btn btn-dark">My Blogs</button></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/"><b><button type="button"
                                    class="btn btn-success">Write</button></b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/"><button type="button" class="btn btn-dark">About</button></a>
                    </li>


                </ul>


            </div>
        </div>
    </nav>

    <form>

        <div class="card">
            <div class="card-body">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">Blog Title</span>
                    <input type="text" class="form-control" id="write_title" name="write_title"
                        placeholder="For eg: Blockchain Technology" aria-label="Sizing example input"
                        aria-describedby="inputGroup-sizing-default" required>
                    <button class="btn btn-outline-success" type="submit"
                        id="a-addon2">&nbsp;&nbsp;&nbsp;&nbsp;POST&nbsp;&nbsp;&nbsp;&nbsp; </button>
                </div>
                <textarea id="write_content" name="write_content" cols="16" rows="5"
                    placeholder="Write the content of your blog."></textarea>
                <script>
                    CKEDITOR.replace('write_content');
                    CKEDITOR.config.height = 500;
                </script>

            </div>
            <div class="card-footer text-muted">
                Author: Rishabh Sinha
            </div>
        </div>

    </form>

    <script>
        function write_info(){

            var write_title_value = document.getElementById("write_title").value;
            var write_content_value = document.getElementById("write_content").value;
        }
    </script>

    <!--Login Form -->


    <!-- Optional JavaScript; choose one of the two! -->
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
        </script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>